CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [FirstName] NVARCHAR(MAX) NOT NULL, 
    [SecondName] NVARCHAR(MAX) NOT NULL, 
    [ThirdName] NVARCHAR(MAX) NOT NULL, 
    [Email] NVARCHAR(MAX) NOT NULL, 
    [PhoneNum] NVARCHAR(MAX) NOT NULL
)
